/*
 * File: app/store/NewsTreeStore.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VeilleAUF.store.NewsTreeStore', {
  extend: 'Ext.data.TreeStore',

  requires: [
    'Ext.data.proxy.JsonP',
    'Ext.data.reader.Json',
    'VeilleAUF.model.news'
  ],

  config: {
    model: 'VeilleAUF.model.news',
    storeId: 'NewsTreeStore',
    proxy: {
      type: 'jsonp',
      url: 'https://outils.vn.auf.org/news/api/?format=jsonp',
      reader: {
        type: 'json',
        totalProperty: 'count'
      }
    }
  }
});