/*
 * File: app/view/NewsContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VeilleAUF.view.NewsContainer', {
  extend: 'Ext.Container',
  alias: 'widget.newsContainer',

  requires: [
    'Ext.XTemplate'
  ],

  config: {
    layout: {
      type: 'fit'
    },
    items: [
      {
        xtype: 'list',
        id: 'dataList',
        itemTpl: [
          '<tpl for="."><div ><img style="padding:0 10px 0px 0px; width:25%; height:15%; float:left;" class="photo" src="{images}" />{titre}<br/> <small style="text-align:justify;"> {extrait_contenu}</small> </div></tpl>'
        ],
        store: 'NewsStore',
        striped: true
      }
    ]
  }

});