/*
 * File: app/view/Pages.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VeilleAUF.view.Pages', {
  extend: 'Ext.tab.Panel',
  alias: 'widget.pages',

  requires: [
    'VeilleAUF.view.NewsContainer'
  ],

  config: {
    items: [
      {
        xtype: 'container',
        title: 'Actualités',
        iconCls: 'info',
        layout: {
          type: 'fit'
        },
        items: [
          {
            xtype: 'newsContainer',
            height: ''
          },
          {
            xtype: 'titlebar',
            docked: 'top',
            title: 'Actualités'
          }
        ]
      },
      {
        xtype: 'container',
        title: 'Système. Académique',
        iconCls: 'compose',
        items: [
          {
            xtype: 'titlebar',
            docked: 'top',
            title: 'Système académique'
          }
        ]
      },
      {
        xtype: 'container',
        title: 'Dossier',
        iconCls: 'bookmarks',
        items: [
          {
            xtype: 'titlebar',
            docked: 'top',
            title: 'Dossier'
          }
        ]
      },
      {
        xtype: 'container',
        title: 'Répertoire',
        iconCls: 'user',
        items: [
          {
            xtype: 'titlebar',
            docked: 'top',
            title: 'Répertoire'
          }
        ]
      }
    ],
    tabBar: {
      docked: 'bottom',
      layout: {
        align: 'center',
        pack: 'center',
        type: 'hbox'
      }
    }
  }

});