/*
 * File: app/model/news.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VeilleAUF.model.news', {
  extend: 'Ext.data.Model',

  requires: [
    'Ext.data.Field'
  ],

  config: {
    fields: [
      {
        name: 'lien_vers_site',
        type: 'string'
      },
      {
        convert: function(v, rec) {
          return v;
        },
        name: 'extrait_contenu',
        type: 'string'
      },
      {
        name: 'titre',
        type: 'string'
      },
      {
        convert: function(v, rec) {
          return "http://outils.vn.auf.org/media/"+v;

        },
        name: 'images',
        type: 'string'
      },
      {
        name: 'id'
      }
    ]
  }
});